//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ClinicInfoDto
{
	id: number;
	slug: string;
	legalName: string;
	displayName: string;
	brandName?: string;
	country?: string;
	region?: string;
	city?: string;
	street?: string;
	postcode?: string;
	phone?: string;
	email?: string;
	website?: string;
	supportHours?: string;
	timezone: string;
	locale: string;
	currency: string;
	theme: string;
	primaryColor?: string;
	secondaryColor?: string;
	backgroundColor?: string;
	textColor?: string;
	logoUrl?: string;
	faviconUrl?: string;
	createdAtUtc: any;
	updatedAtUtc: any;
}
