export const Paths = {
    login: "/login",
    register: "/register",
    app: "/app",
    patientHome: "/app/patient",
    patientWeekDays: "/app/patient/week-days",
    patientSleep: "/app/patient/sleep",
    patientEmotions: "/app/patient/emotions",
    patientMedicines: "/app/patient/medicines",
    patientMedicinesAdd: "/app/patient/medicines/add",
    patientMedicinesEdit: (id: string | number) => `/app/patient/medicines/${id}/edit`,
    patientDiseaseDetails: (id: string | number) => `/app/patient/diseases/${id}`,
    patientChat: "/app/patient/chat",
    patientProfile: "/app/patient/profile",
    doctorHome: "/app/doctor",
    doctorAppointments: "/app/doctor/appointments",
    doctorPatients: "/app/doctor/patients",
    doctorRecords: "/app/doctor/records",
    doctorChat: "/app/doctor/chat",
    doctorInvites: "/app/doctor/invites",
    adminHome: "/app/admin",
    adminUsers: "/app/admin/users",
    adminRoles: "/app/admin/roles",
    adminMemberships: "/app/admin/memberships",
    adminContext: "/app/admin/context",
} as const;
